using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TransformationEngine.Integration.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Only create tables if they don't already exist
            // This handles cases where tables were created manually or by previous processes
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""TransformationConfig"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""EntityType"" character varying(50) NOT NULL,
                    ""Enabled"" boolean NOT NULL,
                    ""Mode"" character varying(20) NOT NULL,
                    ""RuleStorage"" character varying(20) NOT NULL,
                    ""ExternalApiUrl"" character varying(500),
                    ""KafkaEnrichmentEnabled"" boolean NOT NULL,
                    ""KafkaEnrichmentConfig"" jsonb,
                    ""Priority"" integer NOT NULL,
                    ""AllowGeneratedFieldRetransformation"" boolean NOT NULL,
                    ""CustomSettings"" jsonb,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT (NOW()),
                    ""UpdatedAt"" timestamp with time zone NOT NULL DEFAULT (NOW()),
                    CONSTRAINT ""PK_TransformationConfig"" PRIMARY KEY (""Id"")
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""TransformationHistory"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""EntityType"" character varying(50) NOT NULL,
                    ""EntityId"" integer NOT NULL,
                    ""Mode"" character varying(20) NOT NULL,
                    ""RulesApplied"" jsonb,
                    ""TransformationDuration"" bigint NOT NULL,
                    ""Success"" boolean NOT NULL,
                    ""ErrorMessage"" text,
                    ""UsedFallback"" boolean NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT (NOW()),
                    CONSTRAINT ""PK_TransformationHistory"" PRIMARY KEY (""Id"")
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""TransformationJobQueue"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""EntityType"" character varying(50) NOT NULL,
                    ""EntityId"" integer NOT NULL,
                    ""RawData"" jsonb NOT NULL,
                    ""GeneratedFields"" jsonb,
                    ""Status"" character varying(20) NOT NULL,
                    ""RetryCount"" integer NOT NULL,
                    ""ErrorMessage"" text,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT (NOW()),
                    ""ProcessedAt"" timestamp with time zone,
                    ""NextRetryAt"" timestamp with time zone,
                    CONSTRAINT ""PK_TransformationJobQueue"" PRIMARY KEY (""Id"")
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""TransformationRules"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""EntityType"" character varying(50) NOT NULL,
                    ""RuleName"" character varying(100) NOT NULL,
                    ""RuleType"" character varying(50) NOT NULL,
                    ""Configuration"" jsonb NOT NULL,
                    ""Priority"" integer NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CachedFromCentral"" boolean NOT NULL,
                    ""CacheExpiry"" timestamp with time zone,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT (NOW()),
                    ""UpdatedAt"" timestamp with time zone NOT NULL DEFAULT (NOW()),
                    CONSTRAINT ""PK_TransformationRules"" PRIMARY KEY (""Id"")
                );
            ");

            // Create indexes if they don't exist
            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_TransformationConfig_EntityType""
                ON ""TransformationConfig"" (""EntityType"");
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_TransformationHistory_EntityType_EntityId_CreatedAt""
                ON ""TransformationHistory"" (""EntityType"", ""EntityId"", ""CreatedAt"");
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_TransformationJobQueue_EntityType_Status""
                ON ""TransformationJobQueue"" (""EntityType"", ""Status"");
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_TransformationRules_EntityType_RuleName""
                ON ""TransformationRules"" (""EntityType"", ""RuleName"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "TransformationConfig");

            migrationBuilder.DropTable(
                name: "TransformationHistory");

            migrationBuilder.DropTable(
                name: "TransformationJobQueue");

            migrationBuilder.DropTable(
                name: "TransformationRules");
        }
    }
}
